/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author geoffrey fang
 */
public class Front_Page extends javax.swing.JFrame {

    /**
     * Creates new form Front_Page
     */
    public Front_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bookevent = new javax.swing.JButton();
        viewbooking = new javax.swing.JButton();
        cancelbooking = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setMaximumSize(new java.awt.Dimension(770, 775));
        jPanel6.setMinimumSize(new java.awt.Dimension(770, 775));
        jPanel6.setPreferredSize(new java.awt.Dimension(770, 775));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 137, -1, 633));

        bookevent.setBackground(new java.awt.Color(204, 51, 0));
        bookevent.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        bookevent.setForeground(new java.awt.Color(255, 255, 255));
        bookevent.setText("BOOK EVENT");
        bookevent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookeventActionPerformed(evt);
            }
        });
        jPanel6.add(bookevent, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 180, 50));

        viewbooking.setBackground(new java.awt.Color(204, 51, 0));
        viewbooking.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        viewbooking.setForeground(new java.awt.Color(255, 255, 255));
        viewbooking.setText("VIEW BOOKING");
        viewbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbookingActionPerformed(evt);
            }
        });
        jPanel6.add(viewbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 700, 180, 50));

        cancelbooking.setBackground(new java.awt.Color(204, 51, 0));
        cancelbooking.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        cancelbooking.setForeground(new java.awt.Color(255, 255, 255));
        cancelbooking.setText("CANCEL BOOKING");
        cancelbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbookingActionPerformed(evt);
            }
        });
        jPanel6.add(cancelbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 700, 200, 50));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 51));
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/catering pho.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(770, 775));
        jLabel2.setMinimumSize(new java.awt.Dimension(770, 775));
        jLabel2.setPreferredSize(new java.awt.Dimension(770, 775));
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 773, 770));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 775, 776));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbookingActionPerformed
        // TODO add your handling code here:
       viewbooking vb1 = new viewbooking();
       vb1.show();
       
       dispose();
    }//GEN-LAST:event_viewbookingActionPerformed

    private void bookeventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookeventActionPerformed
        // TODO add your handling code here:
       Eventpackage ep1 = new Eventpackage();
       ep1.show();
       
       dispose();
    }//GEN-LAST:event_bookeventActionPerformed

    private void cancelbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbookingActionPerformed
        // TODO add your handling code here:
       cancelledbooking cb1 = new cancelledbooking();
       cb1.show();
       
       dispose();
    }//GEN-LAST:event_cancelbookingActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION
    );

    if (choice == JOptionPane.YES_OPTION) {
        System.exit(0); 
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookevent;
    private javax.swing.JButton cancelbooking;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton viewbooking;
    // End of variables declaration//GEN-END:variables
}
