/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MyConnection.MyConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author geoffrey fang
 */
public class Receptionist extends javax.swing.JFrame {
    

    /**
     * Creates new form Receptionist
     */
    private Connection connect;
    public Receptionist() {
        initComponents();
        MyConnection conn = new MyConnection();
        connect = conn.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlID1 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jlEmail = new javax.swing.JLabel();
        jlContact = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        recepname = new javax.swing.JTextField();
        recepcontact = new javax.swing.JTextField();
        recepemail = new javax.swing.JTextField();
        recepid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlID1.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        jlID1.setForeground(new java.awt.Color(255, 255, 255));
        jlID1.setText("RECEPTIONIST FORM");
        getContentPane().add(jlID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        submit.setBackground(new java.awt.Color(0, 102, 0));
        submit.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 80, 30));

        jlEmail.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlEmail.setText("Receptionist Email:");
        getContentPane().add(jlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jlContact.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlContact.setText("Receptionist Contact Number:");
        getContentPane().add(jlContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jlName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlName.setText("Receptionist Name:");
        getContentPane().add(jlName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jlID.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlID.setText("Receptionist ID:");
        getContentPane().add(jlID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        recepname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepnameActionPerformed(evt);
            }
        });
        getContentPane().add(recepname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 310, 30));

        recepcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepcontactActionPerformed(evt);
            }
        });
        getContentPane().add(recepcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 310, 30));

        recepemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepemailActionPerformed(evt);
            }
        });
        getContentPane().add(recepemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 310, 30));

        recepid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepidActionPerformed(evt);
            }
        });
        getContentPane().add(recepid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 310, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/bkg.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String receptionistName = recepname.getText();
        String contactNumber = recepcontact.getText();
        String email = recepemail.getText();

try {
    if (connect != null) {
        String query = "INSERT INTO receptionist (receptionistName, receptionistNumber, receptionistEmail) VALUES (?, ?, ?)";

        PreparedStatement pst = connect.prepareStatement(query);
        pst.setString(1, receptionistName);
        pst.setString(2, contactNumber);
        pst.setString(3, email);

        int rowsInserted = pst.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Successfully submitted!!");
            Front_Page fp = new Front_Page();
            fp.show();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to submit.");
        }

        pst.close();
    } else {
        JOptionPane.showMessageDialog(this, "Database connection not available!", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    e.printStackTrace();
}

    }//GEN-LAST:event_submitActionPerformed

    private void recepcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recepcontactActionPerformed

    private void recepemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recepemailActionPerformed

    private void recepidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recepidActionPerformed

    private void recepnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recepnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlContact;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlID1;
    private javax.swing.JLabel jlName;
    private javax.swing.JTextField recepcontact;
    private javax.swing.JTextField recepemail;
    private javax.swing.JTextField recepid;
    private javax.swing.JTextField recepname;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
